version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - sudo yum install nginx -y
      - sudo systemctl start nginx
      - sudo systemctl enable nginx

  build:
    commands:
      - echo "Build started on $(date)"
      - sudo cp index.html .

  post_build:
    commands:
      - echo "Configuring NGINX - Done"

artifacts:
  files:
    - '**/*'
