version: 0.2

phases:
  install:
    commands:
      - echo "Insatlling NGINX"
      - sudo apt-get update
      - sudo apt install nginx -y
  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo "Configuring NGINX"

artifacts:
  files:
    - '**/*'
